### ISSUE TITLE
Argparse with city choices generates absurdly long usage message

### ISSUE THREAD

**Issue by Annalgr** [Annalgr/openairquality#17]

**Comment by MarGua21** [comment]
I have removed the choices option by now. I am implementing a function to do a check.

**Comment by MarGua21** [comment]
The check is done in 47a26d689a0399a876c0ef82c1f3a029b9754507

**Comment by MarGua21** [comment]
Function commented in 74cad29e0275f9ea9d2481c15bc1704ed547556d

**Comment by MarGua21** [comment]
Moreover! Now the user can use all lowercase letters when typing city input. Fixed in 6b6a619a27c56f71fde8cc689de9b7f6ab8712ca
