### ISSUE TITLE
Fix the coding style.

### ISSUE THREAD

**Issue by Annalgr** [Annalgr/openairquality#9]

**Comment by Annalgr** [comment]
Done on create_csv 9e91b13e1c73b392c966d40bbbf5b12ded78b30d

**Comment by MarGua21** [comment]
Done on dbmanager b26c8539fce7cefb82d4de9a931757d08694fbcd

**Comment by Annalgr** [comment]
Fixed in:
main.py b5591c495eb194c4fc75be7f9df50a188521cb24
pypackage 79d127a048e66b166e9c4dac03610d282daaf630
scripts bec92acdeea26a89b54e9ebb4972a5049e8bc90d
tests b1a004509ffb45e1f3b7f082aaed753d4a43d5dd
